// Generated by tools/train_tiny_coordinate_mlp.py
import Foundation

public enum TinyWeightVariant: String, CaseIterable, Identifiable, Sendable {
    case activeV7
    case v8Stable
    case v8Novel

    public static let defaultVariant = TinyWeightVariant.activeV7

    public var id: String { rawValue }

    public var title: String {
        switch self {
        case .activeV7:
            return "V7"
        case .v8Stable:
            return "V8 Stable"
        case .v8Novel:
            return "V8 Novel"
        }
    }

    var resourceName: String {
        switch self {
        case .activeV7:
            return "TinyWeights"
        case .v8Stable:
            return "TinyWeightsV8Stable"
        case .v8Novel:
            return "TinyWeightsV8Novel"
        }
    }

    public var trainedSeedCount: Int {
        switch self {
        case .activeV7:
            return 40
        case .v8Stable, .v8Novel:
            return 24
        }
    }

    var promptEncoder: String {
        "compositional_v2"
    }

    var w1Scale: Float {
        switch self {
        case .activeV7:
            return 0.1179008259
        case .v8Stable:
            return 0.03887514805
        case .v8Novel:
            return 0.03365766345
        }
    }

    var w2Scale: Float {
        switch self {
        case .activeV7:
            return 0.01366932373
        case .v8Stable:
            return 0.01189297297
        case .v8Novel:
            return 0.01282002513
        }
    }

    var w3Scale: Float {
        switch self {
        case .activeV7:
            return 0.000853527836
        case .v8Stable:
            return 0.0007167629252
        case .v8Novel:
            return 0.001070610651
        }
    }
}

enum TinyWeights {
    static let latentCount = 64
    static let inputCount = 84
    static let hiddenCount = 1536
    static let hiddenLayerCount = 2
    static let outputCount = 3
    static let defaultVariant = TinyWeightVariant.defaultVariant
    static var trainedSeedCount: Int { defaultVariant.trainedSeedCount }
    static var promptEncoder: String { defaultVariant.promptEncoder }
    static let coordFrequencies: [Float] = [1.0 as Float, 2.0 as Float, 4.0 as Float, 8.0 as Float]
    static var w1Scale: Float { defaultVariant.w1Scale }
    static var w2Scale: Float { defaultVariant.w2Scale }
    static var w3Scale: Float { defaultVariant.w3Scale }
    static let w4Scale = 1.0 as Float
    static var w1: [Float] { storage(for: defaultVariant).w1 }
    static var b1: [Float] { storage(for: defaultVariant).b1 }
    static var w2: [Float] { storage(for: defaultVariant).w2 }
    static var b2: [Float] { storage(for: defaultVariant).b2 }
    static var w3: [Float] { storage(for: defaultVariant).w3 }
    static var b3: [Float] { storage(for: defaultVariant).b3 }
    static var w4: [Float] { [] }
    static var b4: [Float] { [] }

    private static let cache = TinyWeightCache()

    static func storage(for variant: TinyWeightVariant) -> TinyRuntimeWeights {
        cache.storage(for: variant)
    }
}

private final class TinyWeightCache: @unchecked Sendable {
    private let lock = NSLock()
    private var cachedVariant: TinyWeightVariant?
    private var cachedStorage: TinyRuntimeWeights?

    func storage(for variant: TinyWeightVariant) -> TinyRuntimeWeights {
        lock.lock()
        if cachedVariant == variant, let storage = cachedStorage {
            lock.unlock()
            return storage
        }
        lock.unlock()

        let storage = TinyRuntimeWeights.load(variant: variant)

        lock.lock()
        cachedVariant = variant
        cachedStorage = storage
        lock.unlock()
        return storage
    }
}

struct TinyRuntimeWeights: Sendable {
    let variant: TinyWeightVariant
    let w1: [Float]
    let b1: [Float]
    let w2: [Float]
    let b2: [Float]
    let w3: [Float]
    let b3: [Float]

    var promptEncoder: String {
        variant.promptEncoder
    }

    static func load(variant: TinyWeightVariant) -> TinyRuntimeWeights {
        guard let url = Bundle.main.url(forResource: variant.resourceName, withExtension: "bin") ?? developmentWeightURL(resourceName: variant.resourceName) else {
            fatalError("\(variant.resourceName).bin is missing from the app bundle")
        }
        let data: Data
        do {
            data = try Data(contentsOf: url, options: [.mappedIfSafe])
        } catch {
            fatalError("\(variant.resourceName).bin could not be loaded: \(error)")
        }
        var reader = TinyWeightReader(data: data)
        let w1 = reader.readScaledInt8(count: TinyWeights.inputCount * TinyWeights.hiddenCount, scale: variant.w1Scale)
        let b1 = reader.readFloat32(count: TinyWeights.hiddenCount)
        let w2 = reader.readScaledInt8(count: TinyWeights.hiddenCount * TinyWeights.hiddenCount, scale: variant.w2Scale)
        let b2 = reader.readFloat32(count: TinyWeights.hiddenCount)
        let w3 = reader.readScaledInt8(count: TinyWeights.hiddenCount * TinyWeights.outputCount, scale: variant.w3Scale)
        let b3 = reader.readFloat32(count: TinyWeights.outputCount)
        reader.assertFinished()
        return TinyRuntimeWeights(variant: variant, w1: w1, b1: b1, w2: w2, b2: b2, w3: w3, b3: b3)
    }

    private static func developmentWeightURL(resourceName: String) -> URL? {
        let cwd = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)
        let candidates = [
            cwd.appendingPathComponent("\(resourceName).bin"),
            cwd.appendingPathComponent("watchos_example/TinyImageWatchApp/\(resourceName).bin")
        ]
        return candidates.first { FileManager.default.fileExists(atPath: $0.path) }
    }
}

private struct TinyWeightReader {
    let data: Data
    var offset = 0

    mutating func readScaledInt8(count: Int, scale: Float) -> [Float] {
        precondition(offset + count <= data.count, "TinyWeights.bin is truncated")
        var output = [Float]()
        output.reserveCapacity(count)
        for index in offset..<(offset + count) {
            output.append(Float(Int8(bitPattern: data[index])) * scale)
        }
        offset += count
        return output
    }

    mutating func readFloat32(count: Int) -> [Float] {
        var output = [Float]()
        output.reserveCapacity(count)
        for _ in 0..<count {
            output.append(readFloat32())
        }
        return output
    }

    mutating func readFloat32() -> Float {
        precondition(offset + 4 <= data.count, "TinyWeights.bin is truncated")
        var bits: UInt32 = 0
        bits |= UInt32(data[offset])
        bits |= UInt32(data[offset + 1]) << 8
        bits |= UInt32(data[offset + 2]) << 16
        bits |= UInt32(data[offset + 3]) << 24
        offset += 4
        return Float(bitPattern: bits)
    }

    func assertFinished() {
        precondition(offset == data.count, "TinyWeights.bin has unexpected trailing data")
    }
}
