#!/usr/bin/env python3
from __future__ import annotations

import json
import math
import random
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SWIFT_OUT = ROOT / "Sources" / "TinyWatchGenerator" / "TinyWeights.swift"
JSON_OUT = ROOT / "weights" / "tiny_weights.json"

LATENT = 8
INPUT = 6 + LATENT
HIDDEN = 10
OUTPUT = 3


def make_layer(rng: random.Random, rows: int, cols: int, gain: float) -> tuple[list[int], float, list[float]]:
    floats = [rng.gauss(0.0, gain / math.sqrt(cols)) for _ in range(rows * cols)]
    scale = max(max(abs(v) for v in floats) / 127.0, 1e-6)
    q = [max(-127, min(127, int(round(v / scale)))) for v in floats]
    bias = [rng.uniform(-0.35, 0.35) for _ in range(rows)]
    return q, scale, bias


def swift_array_int(name: str, values: list[int]) -> str:
    body = ", ".join(str(v) for v in values)
    return f"    static let {name}: [Int8] = [{body}]"


def swift_array_float(name: str, values: list[float]) -> str:
    body = ", ".join(f"{v:.8} as Float" for v in values)
    return f"    static let {name}: [Float] = [{body}]"


def main() -> None:
    rng = random.Random(260602)
    w1, s1, b1 = make_layer(rng, HIDDEN, INPUT, 1.45)
    w2, s2, b2 = make_layer(rng, HIDDEN, HIDDEN, 1.25)
    w3, s3, b3 = make_layer(rng, OUTPUT, HIDDEN, 1.8)

    JSON_OUT.parent.mkdir(parents=True, exist_ok=True)
    JSON_OUT.write_text(
        json.dumps(
            {
                "latent": LATENT,
                "input": INPUT,
                "hidden": HIDDEN,
                "output": OUTPUT,
                "w1": w1,
                "w1Scale": s1,
                "b1": b1,
                "w2": w2,
                "w2Scale": s2,
                "b2": b2,
                "w3": w3,
                "w3Scale": s3,
                "b3": b3,
            },
            indent=2,
        )
        + "\n"
    )

    source = "\n".join(
        [
            "// Generated by tools/generate_weights.py",
            "enum TinyWeights {",
            f"    static let latentCount = {LATENT}",
            f"    static let inputCount = {INPUT}",
            f"    static let hiddenCount = {HIDDEN}",
            f"    static let outputCount = {OUTPUT}",
            f"    static let w1Scale = {s1:.10} as Float",
            f"    static let w2Scale = {s2:.10} as Float",
            f"    static let w3Scale = {s3:.10} as Float",
            swift_array_int("w1", w1),
            swift_array_float("b1", b1),
            swift_array_int("w2", w2),
            swift_array_float("b2", b2),
            swift_array_int("w3", w3),
            swift_array_float("b3", b3),
            "}",
            "",
        ]
    )
    SWIFT_OUT.write_text(source)

    params = len(w1) + len(w2) + len(w3) + len(b1) + len(b2) + len(b3)
    print(f"wrote {SWIFT_OUT}")
    print(f"wrote {JSON_OUT}")
    print(f"{params} parameters, {len(w1) + len(w2) + len(w3)} int8 weights")


if __name__ == "__main__":
    main()
